# These are supported funding model platforms

github: joaquinamatrodrigo
custom: "https://www.paypal.com/donate?token=EnEsX9vR-KCLV19yCYpKqI1FBjChbnIG2HUVzW6ryu9Fy84gmL3oj7dUoTORPWnaefNAMQtwf5aUz4Yq"
